version: "3.5"
services:
    mysql:
        container_name: axul_event
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        environment:
            - APP_PORT=8081
            - DATABASE_HOST=
            - DATABASE_PORT=3306
            - DATABASE_NAME=axul_event
            - DATABASE_USER=root
            - DATABASE_PASSWORD=
            - DATABASE_DEBUG=true
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
        networks:
            - appnet
networks:
    appnet:
        driver: "bridge"
            